### ISSUE TITLE
The export command fails (produces site with apparently broken javascript)

### ISSUE THREAD

**Issue by virtualinertia** [posit-dev/r-shinylive#122]
The shinylive::export("shiny_app_dir", "site_dir") command fails for me.

It builds a static website structure with apparently broken javascript.

This is a simple Shiny app that works on Posit Cloud and works for everyone when deployed to [shinyapp.io](http://shinyapp.io/) at https://323kwp-alex-karman.shinyapps.io/nld_data_catalog/ .

It is a very simple app with only four files in it, you can clone it from my public github repo at https://github.com/virtualinertia/nld_data_catalog_shiny .

But when I try to convert it by running shinylive::export("nld_data_catalog", "site") it produces a static website in a "site" directory that does not work. The browser freezes. This happens in Posit Cloud but also when I download it and try to run it locally by loading index.html.

**Comment by gadenbuie** [comment]
> it produces a static website in a "site" directory that does not work. The browser freezes. This happens in Posit Cloud

Unfortunately, for technical reasons having to do with the security policies enforced by web browsers, it's not possible to preview a shinylive site from Posit Cloud. Instead, you'll need to either download the exported app to your local machine or upload it to a static web hosting provider (like GitHub Pages or Netlify).

> when I download it and try to run it locally by loading index.html

The reason it doesn't work locally is because you need to run `httpuv::runStaticServer("site")` (replacing `"site"` with the path to the directory where you've downloaded the exported app). Shinylive applications don't work if you simply open `index.html`, they require a web server. `httpuv::runStaticServer()` is an easy way to start a web server from R.

**Comment by virtualinertia** [comment]
Thanks
