### ISSUE TITLE
Detect which packages are used. Automatically install them via `{webr}`

### ISSUE THREAD

**Issue by schloerke** [posit-dev/r-shinylive#16]
If `renv::dependencies("path/to/app")` can be used to detect dependencies, then we can preload app dependencies for users. 

There should not be a requirement for users to call `webr::install("FOO")` to load a precompiled `FOO` package.

**Comment by coatless** [comment]
@schloerke this should be handled by an internal webR API calling R code. I mocked up something for `library()`/`require()` c.f. https://github.com/r-wasm/webr/issues/280

**Comment by georgestagg** [comment]
I think (where possible) I would lean towards using the tools that already exist in `renv` for discovering dependencies, rather than replicating the work in webR.

I am currently working on the next iteration of the webR package building process, and investigating Emscripten's `FS.mount()` API. In principle I think it should be possible to pre-build a Wasm filesystem image containing an R library (defined by `renv`, or a package list, or similar) ready to pre-load into the environment for a given shinylive/webR app.

This should have the additional benefit of being much quicker than downloading, decompressing, and writing many packages from the public package repo to the virtual disk.

**Comment by schloerke** [comment]
r-shinylive seems like the wrong place to do this.  

* Altering the app code to have extra lines seems wrong.
* Even if it worked the first time, it won't automatically work if a new package is added in a shinylive editor.


Seems like it needs to be run in the shinylive R process if the feature is enabled.

**Comment by schloerke** [comment]
Bug fixed in https://github.com/posit-dev/shinylive/pull/68

Shinylive asset support updated in #21 

Closing
