### ISSUE TITLE
Error reading gzip files

### ISSUE THREAD

**Issue by nathanweeks** [posit-dev/r-shinylive#36]
A Shinylive app is able to read from a CSV file, e.g., the shiny 02_text example, altered such that the "rock" data frame is read from a CSV by replacing [this comment](https://github.com/rstudio/shiny-examples/blob/be8967a3e40990f4daae44f1677abb1c3166fc7b/002-text/app.R#L42) with a `read.csv()`:

```bash
Rscript -e 'system.file("examples", "02_text", package="shiny") |> fs::dir_copy("myapp", overwrite = TRUE)'
Rscript -e 'write.csv(rock, file="myapp/rock.csv")'
sed -i '' 's/# Return the requested.*/rock <- read.csv("rock.csv")/' myapp/app.R
Rscript -e 'shinylive::export("myapp", "site")'
Rscript -e 'library(plumber); pr() |> pr_static("/", "site/") |> pr_run()'
```

However, when attempting to read from the same CSV that is gzip-compressed:

```bash
Rscript -e 'system.file("examples", "02_text", package="shiny") |> fs::dir_copy("myapp", overwrite = TRUE)'
Rscript -e 'write.csv(rock, file=gzfile("myapp/rock.csv.gz"))'
sed -i '' 's/# Return the requested.*/rock <- read.csv("rock.csv.gz")/' myapp/app.R
Rscript -e 'shinylive::export("myapp", "site")'
Rscript -e 'library(plumber); pr() |> pr_static("/", "site/") |> pr_run()'
```

The following error is observed in the web browser:

> **Error starting app!**
> Robj construction for this JS object is not yet supported

**Comment by schloerke** [comment]
@georgestagg Any ideas? I couldn't find in docs that gzip compression is/isn't supported. (Thank you!)

**Comment by georgestagg** [comment]
The problem is [here](https://github.com/posit-dev/shinylive/blob/main/src/Components/Viewer.tsx#L173) in the shinylive source. It likely will affect other files encoded in `app.json` when the file has the `type: binary` property.

This works OK for saving text files to the virtual filesystem, but webR is not expecting a binary object here with a content property of type `Uint8Array`.

A small tweak will be required to handle that case better. Probably the `Uint8Array` content should be created in R as a `raw()` R object. I'll take a look at it when I can.

**Comment by schloerke** [comment]
There is a workaround for now. So no immediate rush. Thank you!

**Comment by maek-ies** [comment]
> There is a workaround for now. So no immediate rush. Thank you!

Dear Barret, could you please specify what the workaround is to allow use of gzip files in shinylive? 

I understand that fix by George is yet to be pulled into main shinylive code as the code above still results in the error ("Robj construction for this JS object is not yet supported") and that's why this issue is still open, right?

**Comment by georgestagg** [comment]
This should now work OK.

Please let me know if binary files (e.g. compressed data) are still unable to be exported as part of a Shiny app in a reply below and I can re-open the issue.
