### ISSUE TITLE
ShinyLive Export Error

### ISSUE THREAD

**Issue by quincountychsmn** [posit-dev/r-shinylive#76]
Good afternoon,

I have a working shinyLive application since January. I was updating it today in RStudio and tried to execute the following code (which seemed to work last week) shinylive::export(appdir = "Default Application", destdir = "docs"). However, I receive the following error. Did I miss an update or is this a known issue? 

![image](https://github.com/posit-dev/r-shinylive/assets/153557546/bc890408-5625-4864-b48a-eba44872bc01)

Thank you

**Comment by gadenbuie** [comment]
It looks like you may have installed the dev version of the `httpuv` package from GitHub recently? I think the first thing to try is to follow the instructions in the error message to install `httpuv` from CRAN and try exporting the app again. If that doesn't work, let us know!

**Comment by quinCHB** [comment]
Thank you for the reply. 

I have been using the httpuv dev version since January. I'll run some tests tomorrow. I did try to load the httpuv library and run the export, but I still get the same error. More than likely its user error.

**Comment by quinCHB** [comment]
I was able to remove the dev package with pak::pkg_remove("rstudio/httpuv"). I am now using the CRAN versions for both shinyLive and httpuv. 

I no longer receive the Github API error. However, now I get Error in normalizePath(path.expand(path), winslash, mustWork) : **My Path**: The system cannot find the file specified. 

There are multiple discussions related to this error prior to r-shinyLive. Since I didn't receive this error previously, do you have any suggestions on where I should start? I have exported a shinyLive application successfully and deployed it to [GitHub](https://quinchb.github.io/MN-Public-Health-Data-Access-Portal/). However, it appears I need to update my process to meet the requirements of the new shinyLive changes.

Thank you
