### ISSUE TITLE
Image tags in the UI cause fatal error

### ISSUE THREAD

**Issue by daattali** [posit-dev/r-shinylive#85]
The following app:

```
library(shiny)

ui <- fluidPage(
  tags$img(src="https://raw.githubusercontent.com/rstudio/shiny/main/man/figures/logo.png", width=100),
  "test"
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

Doesn't start up.

I get an error message

```
Robj construction for this JS object is not yet supported
```

![image](https://github.com/posit-dev/r-shinylive/assets/952340/4833b061-2a3e-4c22-8f7f-d3af951d00fe)

**Comment by georgestagg** [comment]
This seems to be working OK [in the shinylive.io editor](https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IIgK60ABAB4AtJIBm1CQBMAClADmcdiMmTSWzgBJaMTV0YEAvELDdSpVJ0QB6V8wDuGTbVLcxejFOOCsScjIMYhgPTlIxFVoiVx4+VlcYKD4MqAhXBVpNMUY4TldqIk0iDFQITTtcSU9aFX9rAEYABk6BXD1JO3I4uxFhUQgQxgA3UJl5BTEIAlIkiHY+VDFSRqItze3JEM5OVYFJEABfERFU-gBBdHYJRsmZxgEwC4BdIA).

That means it is likely that the problem has been fixed in the latest Shinylive assets, and will no longer occur in the R {shinylive} package once it has been updated to use the latest version of the assets.

**Comment by daattali** [comment]
Thanks, it does look to be fixed.
